### ISSUE TITLE
What is output directory

### ISSUE THREAD

**Issue by thealidev** [cwellsx/react-forum#36]
I am trying with vercel and got error
```
Error: No Output Directory named "public" found after the Build completed. You can configure the Output Directory in your Project Settings.
```
Kindly can you help me

**Comment by cwellsx** [comment]
It's been a long time since I looked at this project.
I think you'll find that its output directory is its ./docs folder.
But that depends on how you build it:
- see [Several build targets](https://github.com/cwellsx/view/tree/master/packages/ui-react#several-build-targets)

This project is running "live" here:
- https://cwellsx.github.io/view/

The GitHub configuration for that looks like this:
![image](https://github.com/cwellsx/view/assets/2397556/4d762eeb-87ee-4424-9796-0736a368b9ab)

**Comment by thealidev** [comment]
My project is hosted here :
https://kforums.vercel.app/
Can you help me it does not show anything

**Comment by thealidev** [comment]
I used docs folder

**Comment by thealidev** [comment]
Well
I am using bbpress now
So it's not urgent
But i was just looking at this project

**Comment by cwellsx** [comment]
I can see your page is trying to load resources from a subdirectory named `/view`
Presumably that doesn't exist, it's returning 404

![image](https://github.com/cwellsx/view/assets/2397556/3b194788-c9ed-48b3-99dd-02f60e46f305)

**Comment by thealidev** [comment]
So that's mean project is now dead
